/** English for the survey, keyed by the Spanish source text. */
export const surveyEnglish: Record<string, string> = {
  "Acepto el tratamiento de mis datos según lo descrito.": "I agree to the processing of my data as described.",
  "Autorizo el uso de mis respuestas en forma agregada y anónima.": "I authorize the use of my answers in aggregate and anonymous form.",
  "Quiero recibir el informe y mi benchmark.": "I want to receive the report and my benchmark.",
  "Acepto que Xinergy me invite a la presentación de resultados y me contacte sobre temas relacionados.":
    "I agree that Xinergy may invite me to the results presentation and contact me about related topics.",
  "Muy en desacuerdo": "Strongly disagree",
  "En desacuerdo": "Disagree",
  "Ni de acuerdo ni en desacuerdo": "Neither agree nor disagree",
  "De acuerdo": "Agree",
  "Muy de acuerdo": "Strongly agree",
  Ninguno: "None",
  Bajo: "Low",
  Moderado: "Moderate",
  Alto: "High",
  "Muy alto": "Very high",
  "Muy insatisfecho": "Very dissatisfied",
  Insatisfecho: "Dissatisfied",
  Neutral: "Neutral",
  Satisfecho: "Satisfied",
  "Muy satisfecho": "Very satisfied",
  Nada: "None",
  Poco: "A little",
  Bastante: "Quite a lot",
  Mucho: "A great deal",
  "Nada preparada": "Not prepared at all",
  "Poco preparada": "Slightly prepared",
  Medianamente: "Moderately prepared",
  "Bien preparada": "Well prepared",
  "Totalmente preparada": "Fully prepared",
  "Menos de 10%": "Less than 10%",
  "10–30%": "10–30%",
  "30–50%": "30–50%",
  "50–70%": "50–70%",
  "Más de 70%": "More than 70%",
  "No sé": "I don't know",
  "Eficiencia y valor financiero": "Efficiency and financial value",
  "Riesgo, sostenibilidad y control": "Risk, sustainability and control",
  "Transformación y capacidades": "Transformation and capabilities",
  "Reducir costos": "Reduce costs",
  "Liberar caja y capital de trabajo": "Free up cash and working capital",
  "Gestionar riesgo y continuidad": "Manage risk and continuity",
  "Cumplimiento y control": "Compliance and control",
  "Sostenibilidad y ESG": "Sustainability and ESG",
  "Digitalización e IA": "Digitalization and AI",
  "Innovación con proveedores": "Innovation with suppliers",
  "Talento y capacidades del equipo": "Team talent and capabilities",
  Nombre: "First name",
  Apellido: "Last name",
  "¿Qué cargo describe mejor su rol?": "Which title best describes your role?",
  "CEO / Gerente General": "CEO / General manager",
  "CFO / Gerente de Finanzas": "CFO / Finance manager",
  "CPO / Gerente de Compras o Abastecimiento": "CPO / Procurement or sourcing manager",
  "Gerente de Supply Chain u Operaciones": "Supply chain or operations manager",
  "Otro cargo ejecutivo": "Another executive role",
  "Título exacto del cargo": "Exact job title",
  Empresa: "Company",
  "País donde trabaja": "Country where you work",
  Chile: "Chile",
  México: "Mexico",
  Colombia: "Colombia",
  Perú: "Peru",
  Brasil: "Brazil",
  Argentina: "Argentina",
  Otro: "Other",
  "Años en el cargo actual": "Years in your current role",
  "Menos de 1": "Less than 1",
  "1–3": "1–3",
  "3–5": "3–5",
  "Más de 5": "More than 5",
  "Correo corporativo": "Work email",
  Teléfono: "Phone",
  "Perfil de LinkedIn": "LinkedIn profile",
  "Rubro principal": "Main industry",
  Minería: "Mining",
  "Banca y servicios financieros": "Banking and financial services",
  Seguros: "Insurance",
  "Retail y consumo masivo": "Retail and consumer goods",
  "Forestal, papel y celulosa": "Forestry, paper and pulp",
  "Energía y utilities": "Energy and utilities",
  "Construcción e inmobiliaria": "Construction and real estate",
  "Manufactura e industria": "Manufacturing and industry",
  "Agroindustria y alimentos": "Agribusiness and food",
  "Salud y farmacéutica": "Healthcare and pharmaceuticals",
  "Telecomunicaciones y tecnología": "Telecommunications and technology",
  "Transporte y logística": "Transportation and logistics",
  "Sector público": "Public sector",
  "Tipo de propiedad": "Ownership type",
  "Familiar o privada local": "Family-owned or local private",
  "Abierta en bolsa": "Publicly listed",
  "Filial de multinacional": "Subsidiary of a multinational",
  "Fondo de private equity": "Private equity owned",
  "Estatal o pública": "State-owned or public",
  "Ventas anuales (USD)": "Annual revenue (USD)",
  "Menos de 50 millones": "Less than 50 million",
  "50–250 millones": "50–250 million",
  "250 millones – 1.000 millones": "250 million – 1 billion",
  "1.000 – 5.000 millones": "1–5 billion",
  "Más de 5.000 millones": "More than 5 billion",
  "Prefiero no decir": "I prefer not to say",
  "Gasto anual con proveedores (spend, USD)": "Annual supplier spend (USD)",
  "Menos de 20 millones": "Less than 20 million",
  "20–100 millones": "20–100 million",
  "100–500 millones": "100–500 million",
  "500 millones – 2.000 millones": "500 million – 2 billion",
  "Más de 2.000 millones": "More than 2 billion",
  "Número de empleados": "Number of employees",
  "Menos de 200": "Fewer than 200",
  "200–1.000": "200–1,000",
  "1.000–5.000": "1,000–5,000",
  "Más de 5.000": "More than 5,000",
  "Proveedores activos": "Active suppliers",
  "Menos de 500": "Fewer than 500",
  "500–2.000": "500–2,000",
  "2.000–10.000": "2,000–10,000",
  "Más de 10.000": "More than 10,000",
  "% del gasto que gestiona el área de compras": "% of spend managed by procurement",
  "Modelo de compras": "Procurement model",
  Centralizado: "Centralized",
  Descentralizado: "Decentralized",
  "Híbrido (centro de excelencia + unidades)": "Hybrid (center of excellence + business units)",
  "Personas en el equipo de compras": "People on the procurement team",
  "Menos de 5": "Fewer than 5",
  "5–15": "5–15",
  "15–50": "15–50",
  "Más de 50": "More than 50",
  "Países donde opera la empresa": "Countries where the company operates",
  Otros: "Others",
  "¿Cómo se comparan entre sí las prioridades de compras para su empresa en 2027?": "How do your company's 2027 procurement priorities compare with each other?",
  "Compare primero 3 dimensiones generales y luego las prioridades dentro de cada una. Son 10 comparaciones breves; 1 significa igual importancia y 3–9 indican una preferencia creciente hacia uno de los lados.":
    "First compare 3 overall dimensions, then the priorities within each one. There are 10 short comparisons; 1 means equal importance and 3–9 mean a growing preference toward one side.",
  "¿Cuánto impactarán estos factores su abastecimiento en los próximos 12 meses?": "How much will these factors affect your supply over the next 12 months?",
  "Tipo de cambio": "Exchange rate",
  "Inflación de insumos y servicios": "Inflation in inputs and services",
  "Aranceles y tensiones comerciales (EE.UU., China)": "Tariffs and trade tensions (U.S., China)",
  "Cambios políticos y regulatorios locales": "Local political and regulatory changes",
  "Disrupciones logísticas (puertos, fletes)": "Logistics disruptions (ports, freight)",
  "Conflictos laborales y paros": "Labor disputes and strikes",
  "Clima y eventos naturales": "Climate and natural events",
  "Ciberseguridad de proveedores": "Supplier cybersecurity",
  "En los últimos 12 meses, ¿qué cambios hicieron en su cadena de suministro?": "Over the past 12 months, what changes did you make in your supply chain?",
  "Agregamos proveedores alternativos (dual sourcing)": "We added alternative suppliers (dual sourcing)",
  "Trajimos proveedores más cerca (nearshoring)": "We brought suppliers closer (nearshoring)",
  "Aumentamos inventarios de seguridad": "We increased safety stock",
  "Renegociamos contratos por inflación o tipo de cambio": "We renegotiated contracts because of inflation or exchange rates",
  "Implementamos monitoreo de riesgo de proveedores": "We implemented supplier risk monitoring",
  "Ningún cambio relevante": "No material change",
  "¿Qué tan de acuerdo está con estas afirmaciones sobre riesgo de proveedores?": "How much do you agree with these statements about supplier risk?",
  "Tenemos identificados y clasificados a nuestros proveedores críticos": "We have identified and classified our critical suppliers",
  "Evaluamos periódicamente su riesgo financiero y operacional": "We periodically assess their financial and operational risk",
  "Tenemos planes de contingencia si un proveedor crítico falla": "We have contingency plans if a critical supplier fails",
  "Tenemos alternativas para los proveedores únicos": "We have alternatives for single-source suppliers",
  "Controlamos el cumplimiento laboral, ambiental y legal de los proveedores": "We monitor suppliers' labor, environmental and legal compliance",
  "¿Qué parte de su gasto depende de un proveedor único, sin alternativa inmediata?": "What share of your spend depends on a single supplier, with no immediate alternative?",
  "10–25%": "10–25%",
  "25–50%": "25–50%",
  "Más de 50%": "More than 50%",
  "No lo sabemos": "We don't know",
  "En los últimos 12 meses, ¿sufrió alguno de estos incidentes con proveedores?": "Over the past 12 months, did you experience any of these supplier incidents?",
  "Quiebra o insolvencia de un proveedor": "A supplier's bankruptcy or insolvency",
  "Incumplimiento grave de entrega": "A serious delivery failure",
  "Paralización de operaciones por un proveedor": "Operations stopped because of a supplier",
  "Problema legal, laboral o de compliance": "A legal, labor or compliance issue",
  "Incidente de ciberseguridad": "A cybersecurity incident",
  "¿En qué etapa está el uso de IA en su área de compras?": "What stage is AI use at in your procurement team?",
  "No la usamos": "We don't use it",
  "Uso individual (ChatGPT, Copilot)": "Individual use (ChatGPT, Copilot)",
  "Pilotos formales": "Formal pilots",
  "En producción en algunos procesos": "In production in some processes",
  "Escalada en la mayoría de los procesos": "Scaled across most processes",
  "¿Qué usos de IA tienen hoy o planean en los próximos 12 meses?": "Which AI uses do you have today or plan within the next 12 months?",
  "Análisis y clasificación de gasto": "Spend analysis and classification",
  "Preparación y apoyo a negociaciones": "Negotiation preparation and support",
  "Revisión y gestión de contratos": "Contract review and management",
  "Agentes que compran de forma autónoma (spot, cola larga)": "Agents that buy autonomously (spot, long tail)",
  "Monitoreo de riesgo de proveedores": "Supplier risk monitoring",
  "Conciliación de facturas y P2P": "Invoice matching and P2P",
  "Pronóstico de demanda e inventarios": "Demand and inventory forecasting",
  "Ninguno por ahora": "None for now",
  "¿Cuáles son las 2 principales barreras para adoptar IA?": "What are the 2 main barriers to adopting AI?",
  "Calidad y disponibilidad de datos": "Data quality and availability",
  "Falta de talento o capacidades": "Lack of talent or skills",
  Presupuesto: "Budget",
  "Seguridad y confidencialidad": "Security and confidentiality",
  "ROI poco claro": "Unclear ROI",
  "Integración con sistemas actuales": "Integration with current systems",
  "Resistencia al cambio": "Resistance to change",
  "¿Qué plataformas tecnológicas usan en compras?": "Which technology platforms do you use in procurement?",
  "Marque todas las que apliquen.": "Select all that apply.",
  "SAP ERP (S/4HANA, ECC)": "SAP ERP (S/4HANA, ECC)",
  "SAP Ariba": "SAP Ariba",
  Coupa: "Coupa",
  "GEP SMART": "GEP SMART",
  Oracle: "Oracle",
  Jaggaer: "Jaggaer",
  Ivalua: "Ivalua",
  Zycus: "Zycus",
  Wherex: "Wherex",
  Nimbi: "Nimbi",
  "Mercado Eletrônico": "Mercado Eletrônico",
  "Desarrollo propio": "In-house development",
  "Principalmente Excel y correo": "Mainly Excel and email",
  Otra: "Other",
  "¿Qué tan satisfecho está con su tecnología de compras actual?": "How satisfied are you with your current procurement technology?",
  "¿En qué plazo planea evaluar o incorporar nuevas tecnologías de compras?": "When do you plan to evaluate or adopt new procurement technology?",
  "Estamos evaluando ahora": "We are evaluating now",
  "En los próximos 6 meses": "Within the next 6 months",
  "En 6 a 12 meses": "In 6 to 12 months",
  "En 12 a 24 meses": "In 12 to 24 months",
  "No está en los planes": "It is not in the plans",
  "¿Cómo se gobiernan los datos maestros de proveedores y materiales?": "How are supplier and material master data governed?",
  "Sin dueño: cada área mantiene los suyos": "No owner: each area maintains its own",
  "TI los mantiene, sin reglas de negocio": "IT maintains them, without business rules",
  "Hay reglas, pero no un dueño claro": "There are rules, but no clear owner",
  "Dueño definido y políticas": "A defined owner and policies",
  "Gobierno de datos con control de calidad periódico": "Data governance with periodic quality control",
  "Si hoy le piden cuánto gastó el año pasado con sus 20 principales proveedores, ¿cuánto demora en responder con cifras confiables?":
    "If you were asked today how much you spent last year with your top 20 suppliers, how long would it take to answer with reliable figures?",
  "Minutos: está en un tablero": "Minutes: it is on a dashboard",
  "Menos de un día": "Less than a day",
  "Una semana": "One week",
  "Más de una semana": "More than a week",
  "No podríamos con certeza": "We could not answer with certainty",
  "¿Tiene un rol o responsable dedicado a IA y rediseño de procesos en compras?": "Do you have a role or owner dedicated to AI and process redesign in procurement?",
  "Sí, un rol dedicado": "Yes, a dedicated role",
  "Sí, como parte de otro cargo": "Yes, as part of another role",
  "No, pero tengo autonomía para crearlo": "No, but I have the authority to create it",
  "No, y no depende de mí": "No, and it is not up to me",
  "En los próximos 3 años, ¿la IA le ayudará más a reducir costos o a vender más?": "Over the next 3 years, will AI help you more to reduce costs or to sell more?",
  "Solo a reducir costos": "Only to reduce costs",
  "Más a reducir costos": "More to reduce costs",
  "A ambos por igual": "Both equally",
  "Más a vender": "More to sell",
  "Solo a vender más": "Only to sell more",
  "Ahorro promedio logrado en el último año, como % del gasto gestionado": "Average savings achieved last year, as a % of managed spend",
  "Menos de 2%": "Less than 2%",
  "2–5%": "2–5%",
  "5–8%": "5–8%",
  "8–12%": "8–12%",
  "Más de 12%": "More than 12%",
  "No medimos": "We don't measure it",
  "¿Qué parte del ahorro negociado llega efectivamente al resultado (P&L)?": "What share of negotiated savings actually reaches the P&L?",
  "Menos de 25%": "Less than 25%",
  "50–75%": "50–75%",
  "Más de 75%": "More than 75%",
  "No lo medimos": "We don't measure it",
  "¿Qué tan de acuerdo está con estas afirmaciones sobre su área?": "How much do you agree with these statements about your team?",
  "Finanzas valida nuestros ahorros contra una línea base acordada": "Finance validates our savings against an agreed baseline",
  "Puedo mostrar dónde aparecen los ahorros en el estado de resultados o el balance": "I can show where savings appear in the income statement or the balance sheet",
  "Los ahorros se descuentan del presupuesto del área usuaria": "Savings are taken out of the user area's budget",
  "Hemos rediseñado nuestros procesos de compras en los últimos 2 años": "We have redesigned our procurement processes in the last 2 years",
  "La dirección ve a compras como un socio estratégico": "Leadership sees procurement as a strategic partner",
  "¿Con qué indicadores se evalúa al área de compras?": "Which metrics is the procurement team measured on?",
  "Elija los 3 principales.": "Choose the top 3.",
  "Ahorro vs. presupuesto": "Savings vs. budget",
  "Ahorro vs. último precio": "Savings vs. last price",
  "Impacto en EBITDA": "Impact on EBITDA",
  "Capital de trabajo y caja": "Working capital and cash",
  "Cumplimiento de políticas": "Policy compliance",
  "Nivel de servicio y plazos": "Service level and lead times",
  "Satisfacción de clientes internos": "Internal customer satisfaction",
  "Metas ESG": "ESG targets",
  "¿Cómo evoluciona el presupuesto del área de compras para 2027?": "How is the procurement budget changing for 2027?",
  Baja: "It decreases",
  "Se mantiene": "It stays the same",
  "Sube hasta 10%": "It increases by up to 10%",
  "Sube más de 10%": "It increases by more than 10%",
  "Plazo promedio de pago a proveedores": "Average payment term to suppliers",
  "Menos de 30 días": "Less than 30 days",
  "30–45 días": "30–45 days",
  "45–60 días": "45–60 days",
  "60–90 días": "60–90 days",
  "Más de 90 días": "More than 90 days",
  "¿Cómo describe hoy el rol del área de compras en su empresa?": "How would you describe procurement's role in your company today?",
  "Procesa pedidos": "It processes orders",
  "Negocia precios": "It negotiates prices",
  "Gestiona el costo total": "It manages total cost",
  "Socio en costos, caja y riesgo": "A partner on cost, cash and risk",
  "Participa en las decisiones estratégicas": "It takes part in strategic decisions",
  "¿Cuánto aporta hoy compras en cada dimensión?": "How much does procurement contribute today in each dimension?",
  "Reducción de costos": "Cost reduction",
  "Caja y capital de trabajo": "Cash and working capital",
  "Gestión de riesgo": "Risk management",
  Innovación: "Innovation",
  "Control y cumplimiento": "Control and compliance",
  "¿Qué ahorro espera de compras para 2027, como % del gasto?": "What savings do you expect from procurement for 2027, as a % of spend?",
  "Más de 8%": "More than 8%",
  "No hay meta definida": "There is no defined target",
  "¿Qué palancas de capital de trabajo usan o evalúan?": "Which working-capital levers do you use or evaluate?",
  "Extender plazos de pago": "Extend payment terms",
  "Confirming / supply chain finance": "Confirming / supply chain finance",
  Factoring: "Factoring",
  "Reducir inventarios": "Reduce inventory",
  "Descuento por pronto pago": "Early-payment discounts",
  "Ninguna por ahora": "None for now",
  "¿Qué tan de acuerdo está con estas afirmaciones?": "How much do you agree with these statements?",
  "Los ahorros que reporta compras se ven en el estado de resultados": "The savings procurement reports show up in the income statement",
  "Finanzas valida los ahorros contra una línea base": "Finance validates savings against a baseline",
  "Compras participa en las decisiones de presupuesto e inversión": "Procurement takes part in budget and investment decisions",
  "El área de compras tiene el talento que necesita": "The procurement team has the talent it needs",
  "¿Qué tan conforme está con los resultados del área de compras en el último año?": "How satisfied are you with procurement's results over the past year?",
  "¿Existe hoy un programa formal de reducción de costos en la empresa?": "Is there a formal cost-reduction program in the company today?",
  "Sí, corporativo y con metas por área": "Yes, company-wide and with targets by area",
  "Sí, solo en algunas áreas": "Yes, only in some areas",
  "En diseño": "Being designed",
  No: "No",
  "¿Dónde pone hoy la dirección su energía: en reducir costos o en vender más?": "Where does leadership put its energy today: reducing costs or selling more?",
  "Casi todo en costos": "Almost all on costs",
  "Más en costos": "More on costs",
  Equilibrado: "Balanced",
  "Más en ventas": "More on sales",
  "Casi todo en ventas": "Almost all on sales",
  "Para 2027, el presupuesto para iniciativas de eficiencia (consultoría, tecnología, tercerización)…":
    "For 2027, the budget for efficiency initiatives (consulting, technology, outsourcing)…",
  Sube: "Increases",
  "No está definido": "It is not defined",
  "¿Qué modelo de contratación prefiere para proyectos de eficiencia?": "Which contracting model do you prefer for efficiency projects?",
  "Honorarios fijos": "Fixed fees",
  "Variable según resultados": "Variable, based on results",
  "Mixto: fijo + variable": "Mixed: fixed + variable",
  "Preferimos hacerlo internamente": "We prefer to do it internally",
  "¿Con qué frecuencia se discuten compras y abastecimiento en el directorio?": "How often are procurement and supply discussed at the board?",
  "Casi nunca": "Almost never",
  "Una vez al año": "Once a year",
  Trimestralmente: "Quarterly",
  "Mensualmente o más": "Monthly or more often",
  "¿Qué espera principalmente del área de compras?": "What do you mainly expect from procurement?",
  "Bajar costos": "Lower costs",
  "Mejorar la caja": "Improve cash",
  "Asegurar continuidad operacional": "Secure operational continuity",
  "Habilitar crecimiento e innovación": "Enable growth and innovation",
  "Control y transparencia": "Control and transparency",
  "¿Qué tan preparada está su cadena de suministro para su plan de crecimiento?": "How prepared is your supply chain for your growth plan?",
  "¿A quién reporta el líder de compras?": "Who does the procurement leader report to?",
  "Al CEO": "The CEO",
  "Al CFO": "The CFO",
  "A Operaciones": "Operations",
  "A otra gerencia": "Another function",
  "No hay un líder de compras": "There is no procurement leader",
  "¿Qué parte de su gasto corresponde a servicios y contratistas?": "What share of your spend is services and contractors?",
  "Menos de 30%": "Less than 30%",
  "¿Cuál es su principal riesgo de abastecimiento?": "What is your main supply risk?",
  "Insumos críticos (ácido, explosivos, reactivos)": "Critical inputs (acid, explosives, reagents)",
  "Repuestos y componentes mayores": "Spare parts and major components",
  "Contratistas y mano de obra": "Contractors and labor",
  "Energía y agua": "Energy and water",
  "Logística y puertos": "Logistics and ports",
  "¿Qué parte de su gasto es tecnología (software, nube, servicios TI)?": "What share of your spend is technology (software, cloud, IT services)?",
  "Menos de 20%": "Less than 20%",
  "20–40%": "20–40%",
  "40–60%": "40–60%",
  "Más de 60%": "More than 60%",
  "¿Cómo gestionan el riesgo de terceros que exige el regulador?": "How do you manage the third-party risk the regulator requires?",
  "Gestión básica, caso a caso": "Basic management, case by case",
  "Cumplimos lo mínimo exigido": "We meet the minimum required",
  "Proceso formal con matriz de riesgo": "A formal process with a risk matrix",
  "Proceso formal y automatizado": "A formal, automated process",
  "¿Qué parte de sus compras es importada?": "What share of your purchases is imported?",
  "¿Cuál es hoy su principal presión en compras?": "What is your main procurement pressure today?",
  "Costo de fletes internacionales": "International freight cost",
  "Plazos de entrega": "Delivery lead times",
  "Poder de negociación de grandes marcas": "Bargaining power of major brands",
  "Costos indirectos y de operación": "Indirect and operating costs",
  "¿Cuánto representa mantención y repuestos (MRO) en su gasto total?": "How much do maintenance and spare parts (MRO) represent in total spend?",
  "10–20%": "10–20%",
  "20–35%": "20–35%",
  "Más de 35%": "More than 35%",
  "¿Tienen un programa de optimización de inventario de repuestos?": "Do you have a spare-parts inventory optimization program?",
  "Sí, parcial": "Yes, partial",
  "Sí, con resultados medidos": "Yes, with measured results",
  "¿Qué parte de sus compras se hace por trato directo o compra ágil?": "What share of your purchases is made by direct award or simplified buying?",
  "¿Cuál es su principal desafío en compras públicas?": "What is your main challenge in public procurement?",
  "Plazos de licitación": "Tender timelines",
  Normativa: "Regulation",
  "Capacidades del equipo": "Team capabilities",
  Tecnología: "Technology",
  "Poca participación de proveedores": "Low supplier participation",
  "¿Qué parte del gasto es insumos clínicos y farmacéuticos?": "What share of spend is clinical and pharmaceutical supplies?",
  "Quiebres de stock": "Stockouts",
  "Dependencia de importaciones": "Dependence on imports",
  "Regulación sanitaria": "Health regulation",
  "Alzas de precios": "Price increases",
  "¿Qué proyectos tienen planificados para los próximos 12–18 meses?": "Which projects do you have planned for the next 12–18 months?",
  "Transformación del modelo de compras": "Procurement model transformation",
  "Implementar o cambiar plataforma de compras": "Implement or change the procurement platform",
  "Olas de ahorro y renegociación": "Savings waves and renegotiation",
  "Tercerizar parte de compras (BPO)": "Outsource part of procurement (BPO)",
  "Programa de confirming o supply chain finance": "A confirming or supply chain finance program",
  "Optimización de inventarios": "Inventory optimization",
  "Gestión de riesgo de proveedores": "Supplier risk management",
  "ESG en la cadena de suministro": "ESG in the supply chain",
  "Ninguno definido": "None defined",
  "¿Qué actividades de compras tercerizaría?": "Which procurement activities would you outsource?",
  "Compras tácticas y cola larga": "Tactical and long-tail buying",
  "Licitaciones de categorías específicas": "Tenders for specific categories",
  "Procesamiento de órdenes y facturas (P2P)": "Order and invoice processing (P2P)",
  "Registro y evaluación de proveedores": "Supplier registration and evaluation",
  "Analítica de gasto": "Spend analytics",
  Ninguna: "None",
  "¿Qué tan de acuerdo está con estas afirmaciones sobre presupuesto y equipo?": "How much do you agree with these statements about budget and team?",
  "Tengo presupuesto aprobado para los proyectos de 2027": "I have an approved budget for the 2027 projects",
  "Tengo presupuesto para contratar mejor talento": "I have budget to hire better talent",
  "Mi equipo tiene las capacidades para los desafíos de 2027": "My team has the capabilities for the 2027 challenges",
  "Puedo crear roles nuevos en el equipo (IA, datos, procesos)": "I can create new roles on the team (AI, data, processes)",
  "Retener talento en compras es más difícil que hace 2 años": "Retaining procurement talent is harder than it was 2 years ago",
  "¿Cuántas vacantes tiene hoy abiertas en su equipo de compras?": "How many open roles do you have on your procurement team today?",
  "1–2": "1–2",
  "¿Cuánto tardan en promedio en llenar una vacante de compras?": "How long does it take, on average, to fill a procurement role?",
  "Menos de 1 mes": "Less than 1 month",
  "1–3 meses": "1–3 months",
  "3–6 meses": "3–6 months",
  "Más de 6 meses": "More than 6 months",
  "Rotación anual aproximada del equipo de compras": "Approximate annual turnover of the procurement team",
  "Menos de 5%": "Less than 5%",
  "5–10%": "5–10%",
  "Más de 20%": "More than 20%",
  "¿Qué 3 capacidades son más difíciles de encontrar?": "Which 3 capabilities are hardest to find?",
  "Negociación avanzada": "Advanced negotiation",
  "Análisis de datos": "Data analysis",
  "IA y herramientas digitales": "AI and digital tools",
  "Expertise técnica por categoría": "Technical category expertise",
  "Visión financiera": "Financial acumen",
  "Liderazgo y gestión del cambio": "Leadership and change management",
  Sostenibilidad: "Sustainability",
  "¿Qué temas le interesa profundizar en el informe o en próximos encuentros?": "Which topics would you like to explore in the report or at future meetings?",
  "IA aplicada a compras": "AI applied to procurement",
  "Riesgo y resiliencia": "Risk and resilience",
  "Talento y modelo organizacional": "Talent and operating model",
  "Benchmarks de ahorro por industria": "Savings benchmarks by industry",
  "Tercerización de compras": "Procurement outsourcing",
  "Plataformas y tecnología": "Platforms and technology",
  "ESG en proveedores": "ESG in the supplier base",
  "¿Cuál es el mayor desafío de su área para 2027?": "What is your team's biggest challenge for 2027?",
};
