export type ClientLogo = { name: string; src: string };

/** Logos de clientes en /public/clients — orden editorial. Chubb omitido: asset origen corrupto. */
export const clientLogos: readonly ClientLogo[] = [
  { name: "Banco de Chile", src: "/clients/banco_de_chile.png" },
  { name: "BCP", src: "/clients/BCP.png" },
  { name: "Itaú", src: "/clients/itau.png" },
  { name: "Scotiabank Colpatria", src: "/clients/scotiabank_colpatria.png" },
  { name: "Transbank", src: "/clients/transbank.png" },
  { name: "Supervielle", src: "/clients/supervielle.png" },
  { name: "BanBif", src: "/clients/Banbif_logo.svg.png" },
  { name: "Banco Ripley", src: "/clients/Banco_ripley.png" },
  { name: "Coopeuch", src: "/clients/Coopeuch.png" },
  { name: "Consorcio", src: "/clients/Consorcio.png" },
  { name: "Grupo Security", src: "/clients/Grupo_security.png" },
  { name: "Chilena Consolidada", src: "/clients/chilena_consolidada.png" },
  { name: "Sura", src: "/clients/Sura.png" },
  { name: "Zurich", src: "/clients/zurich.png" },
  { name: "CLARO", src: "/clients/CLARO.png" },
  { name: "CMPc", src: "/clients/cmpc.png" },
  { name: "Celsia", src: "/clients/celsia.png" },
  { name: "ESVAL", src: "/clients/ESVAL.png" },
  { name: "Bimbo", src: "/clients/BIMBO.png" },
  { name: "Unilever", src: "/clients/unilever.png" },
  { name: "Softys", src: "/clients/softys.png" },
  { name: "Megalabs", src: "/clients/Megalabs.png" },
  { name: "Audifarma", src: "/clients/audifarma.png" },
  { name: "ITF Labomed", src: "/clients/itf_labomed_transparente.png" },
  { name: "AMSA", src: "/clients/Amsa.png" },
  { name: "Marcobre", src: "/clients/Marcobre.png" },
  { name: "Huchipat", src: "/clients/Huchipato.png" },
  { name: "Manuka", src: "/clients/Manuka.png" },
  { name: "Flesan", src: "/clients/Flesan.png" },
  { name: "Brinks", src: "/clients/BRINKS.png" },
  { name: "Derco", src: "/clients/Derco.png" },
  { name: "Indumotora", src: "/clients/Indumotora.png" },
  { name: "Inchcape", src: "/clients/inchcape.png" },
  { name: "Gentera", src: "/clients/Gentera.png" },
  { name: "SAAM", src: "/clients/Saam.png" },
  { name: "Botero Soto", src: "/clients/botero_soto.png" },
  { name: "Banmedica", src: "/clients/banme_dica.png" },
  { name: "Teletón", src: "/clients/teleton.png" },
] as const;
